### ISSUE TITLE
Atualizando o modelo do vosk

### ISSUE THREAD

**Issue by gabrielroses15** [falabrasil/kaldi-br#14]
Olá bom dia, eu gostaria de saber como consigo pegar áudios e suas transcrições manuais para adicionar este conteúdo no conteúdo do modelo do vosk, pois gostaria de adicionar conteúdo e "treinar" o vosk com mais áudios e transcrições, existe uma pasta onde eu coloque os áudios, suas respectivas transcrições e rode algum programa para transformar isto em um modelo do vosk?

**Comment by cassiotbatista** [comment]
Oi,

Sim, mas precisas aprender a usar o Kaldi, o que nao e' tao trivial. A recomendacao e' comecar pela recipe com a LapsBM (`fb-lapsbm`): https://github.com/falabrasil/kaldi-br?tab=readme-ov-file#model-training-for-speech-recognition-vosk--lapsbm 

Ver tambem: https://alphacephei.com/vosk/models#training-your-own-model

**Comment by gabrielroses15** [comment]
Só consigo fazer isto em um SO linux?
