### ISSUE TITLE
Adicionar dados

### ISSUE THREAD

**Issue by gabrielroses15** [falabrasil/kaldi-br#15]
rodar o run_them_all do fb-lapsbm com mais audios e os diretórios configurados irá treinar meu próprio modelo para eu usar ou é mais complicado do que isto?

**Comment by cassiotbatista** [comment]
Mais complicado que isso. A recipe `fb-falabrasil` executa em todos os datasets usados para treinar o atual modelo que disponibilizamos para o Vosk.

No mais, as issues aqui do GitHub deveriam ser abertar apenas para problemas reais. Se fores criar outra, espero que seja apos passares tempo lendo os READMEs, experimentando e entendendo os scripts, e olhando os dados e outros repositorios que existem no GitHub do FalaBrasil (boa parte das infos estao la).

Nao sei por que decidiste comecar a mexer com ASR, mas nao e' assim, fazendo esse tipo de pergunta, que funciona, especialmente com pesquisa e projetos open-source. Se estiveres perdido ou com dificuldade, sugiro que "percas mais tempo metendo a mao na massa" sozinho ou encontres alguem que de fato te oriente.

**Comment by gabrielroses15** [comment]
a idéia era o criador (você) me orientar, desculpe
