### ISSUE TITLE
Modelo vosk não funciona em java

### ISSUE THREAD

**Issue by Shisuiicaro** [falabrasil/kaldi-br#16]
Então, eu tenho um mod de minecraft que utiliza modelos vosk para reconhecimento de fala, e ao testar o modelo treinado por vocês ele não funciona, somente com outros modelos, inclusive com o modelo small (que ta bem ruim)

**Comment by Shisuiicaro** [comment]
De acordo com os meus testes o modelo so funciona se eu tirar o arquivod G.carpa, se não tirar ele da "failed to create model", alguma maneira de resolver isso?

**Comment by Shisuiicaro** [comment]
LOG (VoskAPI:ReadDataFiles():model.cc:317) Loading CARPA model from C:\Users\gnarn\Fabric-Microphone-Text-Input\run\.mcmti\model-fb-v0.1.1-20220516_2113/rescore/G.carpa
ERROR (VoskAPI:ReadInternal():const-arpa-lm.cc:610) ConstArpaLm <LmStates> section reading failed.

**Comment by cassiotbatista** [comment]
Oi,

Pelo que estas relatando, podes simplesmente remover a pasta `rescore` como um todo. Na linguagem que o pessoal do Vosk usa, isso vai converter o modelo de "big" para "small".
