### ISSUE TITLE
adapting the gentle model

### ISSUE THREAD

**Issue by kelseyjd** [falabrasil/kaldi-br#17]
Hello, I was hoping to train a model to do alignment with Gentle. I saw that you also tried this but had version mismatch issues. Do you have any ideas about how to modify the code or checkpoints to make it work?

**Comment by cassiotbatista** [comment]
Hi,

It's been quite a while now, I don't really remember what went wrong. As far as I can tell, Gentle uses its own fork of Kaldi which is behind trunk, so you could try rolling some commits back and use the old scripts from Kaldi as such.

I may be wrong tho, so you better investigate whether that is the real problem in the first place.

Finally, I don't see how using Gentle over MFA at this point would help. My experiments didn't show any improvement by using nnet-based models w.r.t. gmm-based ones for forced alignment.

**Comment by cassiotbatista** [comment]
Closing due to 2 weeks of inactivity. Please re-open it if needed.
