### ISSUE TITLE
Gente, onde está o link do modelo do vosk? 

### ISSUE THREAD

**Issue by iceFbr** [falabrasil/kaldi-br#4]

**Comment by cassiotbatista** [comment]
Oi, não temos modelos pré-treinados para o Vosk, apenas scripts que treinam um modelo _dummy_ sobre a base da LapsBenchmark.

O Vosk, no entanto, possui um [modelo para Português Brasileiro no próprio site](https://alphacephei.com/vosk/models/vosk-model-small-pt-0.3.zip).
