### ISSUE TITLE
Modelo para Vosk

### ISSUE THREAD

**Issue by wedersonrsouza** [falabrasil/kaldi-br#6]
Alguém sabe onde posso encontrar um modelo para o Vosk com uma qualidade melhor do que o que está disponível no site deles?

**Comment by cassiotbatista** [comment]
Oi,

Temos um plano para treinar um modelo para o vosk, mas ainda sem previsão de conclusão (#4). Até onde sei, o do site é o único para PT_BR.

No entanto, existem coisas fora do universo do Vosk, e.g. um [fine-tuning do wav2vec2 com modelo disponível no hugging face](https://arxiv.org/abs/2107.11414).
