### ISSUE TITLE
[fb-falabrasil] local: write tailored data prep scripts

### ISSUE THREAD

**Issue by cassiotbatista** [falabrasil/kaldi-br#7]
- [x] CETUC
- [x] LapsBM
- [x] Código de Defesa do Consumidor
- [x] Constituição
- [x] CORAA
- [x] CV
- [x] LapsStory
- [x] WestPoint
- [x] Spoltech
- [x] VoxForge
- [x] MLS
- [x] mTEDx

**Comment by cassiotbatista** [comment]
all falabrasil "traditional" datasets are treated by the same script, which parses a `*.list` file that accompanies the dataset on DVC.

**Comment by cassiobatista** [comment]
note to self: maybe prep_data script from librispeech recipe can be borrowed to process mls portuguese?

**Comment by cassiotbatista** [comment]
normalizer for mtedx transcriptions still needs some work. lots of errors on the training set
